In [3]:
from scipy.optimize import linear_sum_assignment
import numpy as np

In [4]:
my_arr = np.array([[5, 1, 17],[12, 6, 19], [3, 2, 7]])
print(my_arr, my_arr.shape)

[[ 5  1 17]
 [12  6 19]
 [ 3  2  7]] (3, 3)


In [7]:
row_ind, col_ind = linear_sum_assignment(my_arr)
print(my_arr[row_ind, col_ind].sum())

row_ind, col_ind = linear_sum_assignment(-my_arr)
print(my_arr[row_ind, col_ind].sum())

18
31
