In [15]:
from scipy.io import loadmat, savemat
import numpy as np

In [30]:
f = loadmat('train_32x32.mat')
x_train = np.reshape(f['X'], (32 * 32 * 3, f['X'].shape[3])).T
y_train = np.subtract(np.squeeze(f['y']), 2)
y_train[y_train==255] = 9
print(np.unique(y_train))

[0 1 2 3 4 5 6 7 8 9]


In [31]:
f = loadmat('test_32x32.mat')
x_test = np.reshape(f['X'], (32 * 32 * 3, f['X'].shape[3])).T
y_test = np.subtract(np.squeeze(f['y']), 2)
y_test[y_test==255] = 9
print(np.unique(y_test))

[0 1 2 3 4 5 6 7 8 9]


In [22]:
x_test.shape

(26032, 3072)

In [44]:
for i in range(40):
    path_train = f'SVHN_x_train{i}.npy'
    path_test = f'SVHN_x_test{i}.npy'
    if i == 0:
        x_train = np.load(path_train)
        x_test = np.load(path_test)
    elif i < 20:
        x_train = np.concatenate((x_train, np.load(path_train)))
        x_test = np.concatenate((x_test, np.load(path_test)))
    else:
        x_train = np.concatenate((x_train, np.load(path_train)))
    print(i, x_train.shape, x_test.shape)

0 (1878, 3072) (1370, 3072)
1 (3756, 3072) (2740, 3072)
2 (5634, 3072) (4110, 3072)
3 (7512, 3072) (5480, 3072)
4 (9390, 3072) (6850, 3072)
5 (11268, 3072) (8220, 3072)
6 (13146, 3072) (9590, 3072)
7 (15024, 3072) (10960, 3072)
8 (16902, 3072) (12330, 3072)
9 (18780, 3072) (13700, 3072)
10 (20658, 3072) (15070, 3072)
11 (22536, 3072) (16440, 3072)
12 (24414, 3072) (17810, 3072)
13 (26292, 3072) (19180, 3072)
14 (28170, 3072) (20550, 3072)
15 (30048, 3072) (21920, 3072)
16 (31926, 3072) (23290, 3072)
17 (33804, 3072) (24660, 3072)
18 (35682, 3072) (26030, 3072)
19 (37560, 3072) (26032, 3072)
20 (39438, 3072) (26032, 3072)
21 (41316, 3072) (26032, 3072)
22 (43194, 3072) (26032, 3072)
23 (45072, 3072) (26032, 3072)
24 (46950, 3072) (26032, 3072)
25 (48828, 3072) (26032, 3072)
26 (50706, 3072) (26032, 3072)
27 (52584, 3072) (26032, 3072)
28 (54462, 3072) (26032, 3072)
29 (56340, 3072) (26032, 3072)
30 (58218, 3072) (26032, 3072)
31 (60096, 3072) (26032, 3072)
32 (61974, 3072) (26032, 3072)

In [42]:
#np.save('SVHN_y_train.npy', y_train)
#np.save('SVHN_y_test.npy', y_test)

print(x_train.shape)
batches = 40
total = x_train.shape[0]
batch_size = round(total/(batches-1),0)
for i in range(batches):
    first = int(i*batch_size)
    last = int(min((i+1)*batch_size, total))
    print(first, last)
    file = f'SVHN_x_train{i}.npy'
    this_x = x_train[first:last]
    print(last - first, this_x.shape)
    np.save(file, this_x)

print(x_test.shape)
batches = 20
total = x_test.shape[0]
batch_size = round(total/(batches-1),0)
for i in range(batches):
    first = int(i*batch_size)
    last = int(min((i+1)*batch_size, total))
    print(first, last)
    file = f'SVHN_x_test{i}.npy'
    this_x = x_test[first:last]
    print(last - first, this_x.shape)
    np.save(file, this_x)

(73257, 3072)
0 1878
1878 (1878, 3072)
1878 3756
1878 (1878, 3072)
3756 5634
1878 (1878, 3072)
5634 7512
1878 (1878, 3072)
7512 9390
1878 (1878, 3072)
9390 11268
1878 (1878, 3072)
11268 13146
1878 (1878, 3072)
13146 15024
1878 (1878, 3072)
15024 16902
1878 (1878, 3072)
16902 18780
1878 (1878, 3072)
18780 20658
1878 (1878, 3072)
20658 22536
1878 (1878, 3072)
22536 24414
1878 (1878, 3072)
24414 26292
1878 (1878, 3072)
26292 28170
1878 (1878, 3072)
28170 30048
1878 (1878, 3072)
30048 31926
1878 (1878, 3072)
31926 33804
1878 (1878, 3072)
33804 35682
1878 (1878, 3072)
35682 37560
1878 (1878, 3072)
37560 39438
1878 (1878, 3072)
39438 41316
1878 (1878, 3072)
41316 43194
1878 (1878, 3072)
43194 45072
1878 (1878, 3072)
45072 46950
1878 (1878, 3072)
46950 48828
1878 (1878, 3072)
48828 50706
1878 (1878, 3072)
50706 52584
1878 (1878, 3072)
52584 54462
1878 (1878, 3072)
54462 56340
1878 (1878, 3072)
56340 58218
1878 (1878, 3072)
58218 60096
1878 (1878, 3072)
60096 61974
1878 (1878, 3072)
61974 6385

In [43]:
1878*39 + 15

73257

In [41]:
x_train[73255:73257]

array([[190, 188, 191, ..., 218, 213, 209],
       [216, 217, 212, ..., 181, 178, 171]], dtype=uint8)